spring:  
  application:
    name: ignite-rest-service
  datasource:
    name: mysqlds
    url: jdbc:mysql://localhost:3306/ignite?useSSL=false
    username: ignite
    password: ignite123
             
server:  
  port: ${PORT:8090}
  
management:
  security:
    enabled: false